[server]
host = "127.0.0.1"
port = 8080
timeout = "4s"
idle_timeout = "30s"

[storage]
type = "sql"

[database]
host="127.0.0.1"
port=5432
username="postgres"
password="ChangeMe"
database="calendar"

[logger]
level = "info"
